# This workflow will build and upload a Docker image when a new tag is pushed

name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set tag output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build the Docker image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ steps.vars.outputs.tag }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker build . --file Dockerfile --tag netapp/astra-toolkits:latest --tag netapp/astra-toolkits:$DOCKERIMAGE_TAG

    - name: Push the Docker image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ steps.vars.outputs.tag }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker push netapp/astra-toolkits:latest
        docker push netapp/astra-toolkits:$DOCKERIMAGE_TAG
